---
# Main config file for the Signal plugin.
#
# It should contain key-value pairs of people who can be sent a signal,
# where the key is the name or nickname of the person, and the value is
# the the phone email address (for email text messages) to send the
# message to. See below article to translate a phone number to a email
# address to send a text message to:
#   https://github.com/mfitzp/List_of_SMS_gateways/

user1: '5035554444@txt.att.net'
user2: '9714445555@txt.att.net'
